remote_theme: dracula/gh-pages
plugins:
  - jekyll-remote-theme

show_downloads: true
show_header: true

github:
  owner_name: Griffin
  owner_url: https://github.com/dsgriffin
  repository_url: https://github.com/dsgriffin/dsgriffin.github.io

title: Early NFTs
description: All about vintage blockchain collectibles
